In [43]:
import pandas as pd
d1=pd.read_csv("C:\\Users\\atchu\\Downloads\\Myopia-study-classification-logistic-regression-R-master\\Myopia-study-classification-logistic-regression-R-master\\dataset\\myopia.csv")
#print(d1)
print(d1.head())
d1.describe()

   ID  STUDYYEAR  MYOPIC  AGE  GENDER  SPHEQ     AL    ACD     LT    VCD  \
0   1       1992       1    6       1 -0.052  21.89  3.690  3.498  14.70   
1   2       1995       0    6       1  0.608  22.38  3.702  3.392  15.29   
2   3       1991       0    6       1  1.179  22.49  3.462  3.514  15.52   
3   4       1990       1    6       1  0.525  22.20  3.862  3.612  14.73   
4   5       1995       0    5       0  0.697  23.29  3.676  3.454  16.16   

   SPORTHR  READHR  COMPHR  STUDYHR  TVHR  DIOPTERHR  MOMMY  DADMY  
0       45       8       0        0    10         34      1      1  
1        4       0       1        1     7         12      1      1  
2       14       0       2        0    10         14      0      0  
3       18      11       0        0     4         37      0      1  
4       14       0       0        0     4          4      1      0  


ID    STUDYYEAR      MYOPIC         AGE      GENDER  \
count  618.000000   618.000000  618.000000  618.000000  618.000000   
mean   309.500000  1992.359223    0.131068    6.299353    0.488673   
std    178.545512     1.734507    0.337748    0.712950    0.500277   
min      1.000000  1990.000000    0.000000    5.000000    0.000000   
25%    155.250000  1991.000000    0.000000    6.000000    0.000000   
50%    309.500000  1992.000000    0.000000    6.000000    0.000000   
75%    463.750000  1994.000000    0.000000    6.000000    1.000000   
max    618.000000  1995.000000    1.000000    9.000000    1.000000   

            SPHEQ          AL         ACD          LT         VCD     SPORTHR  \
count  618.000000  618.000000  618.000000  618.000000  618.000000  618.000000   
mean     0.801010   22.496780    3.578629    3.541453   15.376780   11.953074   
std      0.625918    0.680141    0.230394    0.154519    0.664183    7.968296   
min     -0.699000   19.900000    2.772000    2.960000   13.380000    0.000000   
25%      0.456250   22.040000    3.424000    3.436000   14.930000    6.000000   
50%      0.729000   22.465000    3.585000    3.542000   15.360000   10.000000   
75%      1.034000   22.970000    3.730000    3.640000   15.840000   16.000000   
max      4.372000   24.560000    4.250000    4.112000   17.300000   45.000000   

           READHR      COMPHR     STUDYHR        TVHR   DIOPTERHR       MOMMY  \
count  618.000000  618.000000  618.000000  618.000000  618.000000  618.000000   
mean     2.796117    2.105178    1.490291    8.948220   26.017799    0.506472   
std      3.068191    3.056508    2.216207    5.719021   16.031715    0.500363   
min      0.000000    0.000000    0.000000    0.000000    2.000000    0.000000   
25%      0.000000    0.000000    0.000000    4.250000   15.000000    0.000000   
50%      2.000000    1.000000    1.000000    8.000000   23.000000    1.000000   
75%      4.000000    3.000000    2.000000   12.000000   34.000000    1.000000   
max     20.000000   30.000000   15.000000   31.000000  101.000000    1.000000   

            DADMY  
count  618.000000  
mean     0.498382  
std      0.500402  
min      0.000000  
25%      0.000000  
50%      0.000000  
75%      1.000000  
max      1.000000

In [44]:
d1.shape
d1['MYOPIC']

0      1
1      0
2      0
3      1
4      0
      ..
613    1
614    0
615    0
616    0
617    0
Name: MYOPIC, Length: 618, dtype: int64

In [45]:
import numpy as np
y=np.array(d1['MYOPIC'])
print(y)
#x=np.array(d1['STUDYYEAR','AGE','GENDER','SPHEQ','AL','ACD','LT','VCD','SPORTHR','READHR','COMPHR',''])

[1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0
 0 0 1 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 1 0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 1 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 1 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 1 1 0 0 0 0 0 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0
 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 1
 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 0 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0
 0 0 0 1 0 0 0 0 0 1 0 0 

In [65]:
d3=pd.read_csv("C:\\Users\\atchu\\Downloads\\Myopia-study-classification-logistic-regression-R-master\\Myopia-study-classification-logistic-regression-R-master\\dataset\\myopia.csv")
del d3['MYOPIC']
#print(d3)
#print(d3[['SPHEQ','VCD','AL','ACD','VCD']])
X=np.array(d3)
# #print(d3.shape)
# #print(d3.head())
print(X)

[[1.000e+00 1.992e+03 6.000e+00 ... 3.400e+01 1.000e+00 1.000e+00]
 [2.000e+00 1.995e+03 6.000e+00 ... 1.200e+01 1.000e+00 1.000e+00]
 [3.000e+00 1.991e+03 6.000e+00 ... 1.400e+01 0.000e+00 0.000e+00]
 ...
 [6.160e+02 1.995e+03 6.000e+00 ... 4.000e+00 1.000e+00 1.000e+00]
 [6.170e+02 1.991e+03 6.000e+00 ... 2.300e+01 0.000e+00 0.000e+00]
 [6.180e+02 1.994e+03 6.000e+00 ... 1.400e+01 1.000e+00 1.000e+00]]


In [83]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.75, random_state=42)

In [84]:
X_train.shape

(154, 17)

In [85]:
X_test.shape

(464, 17)

In [86]:
mclf=LogisticRegression(max_iter=10000).fit(X_train,y_train)
#print(mclf)

In [90]:
y_pred=mclf.predict(np.array(X_test))



#mclf.score(X_train,y_train)
#mclf.score(X_test,y_test)



In [89]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(mclf, X_train, y_train, cv=5)
scores

array([0.87096774, 0.93548387, 0.83870968, 0.83870968, 0.9       ])

In [91]:
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[393,  11],
       [ 48,  12]], dtype=int64)